project:
  type: website
  title: "Sustainability Research Bootcamp"
  output-dir: docs

website:
  title: "Sustainability Research Bootcamp"
  description: "10-Day Intensive ML & Research Methods Program | Sustainability Lab, IIT Gandhinagar"
  site-url: "https://sustainability-lab.github.io/sustainability-research-bootcamp"
  repo-url: "https://github.com/sustainability-lab/sustainability-research-bootcamp"
  
  navbar:
    logo: "assets/logo.svg"
    title: "Sustainability Research Bootcamp"
    background: "#2E8B57"
    foreground: "#FFFFFF"
    left:
      - text: "Home"
        file: index.qmd
      - text: "Program"
        file: program.qmd
    right:
      - icon: github
        href: "https://github.com/sustainability-lab/sustainability-research-bootcamp"
      - icon: globe
        href: "https://sustainability-lab.github.io/"

  page-footer:
    left: |
      © 2025 Sustainability Lab, IIT Gandhinagar
    right: |
      Built with [Quarto](https://quarto.org)
    center: |
      Contact: [nipun.batra@iitgn.ac.in](mailto:nipun.batra@iitgn.ac.in)

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: true
    toc-depth: 3
    toc-location: right
    number-sections: false
    code-copy: true
    code-fold: false
    highlight-style: github
    fontsize: 1.1em
    linestretch: 1.7
    link-external-newwindow: true
    mermaid:
      theme: default

execute:
  freeze: auto
  echo: true
  warning: false
  error: false